### ISSUE TITLE
Error uploading .10 extension with text/plain type

### ISSUE THREAD

**Issue by sanzeeb3** [awesomemotive/file-upload-types#12]
The file when uploading from **Media > Library > Add New**, the file fails before checking for wp_check_filetype_and_ext().

The file when uploading from **Media > Add New**, the wp_check_filetype_and_ext() returns empty file data.

```
Array
(
    [ext] => 
    [type] => 
    [proper_filename] => 
)
```

[](url)

**Comment by jaredatch** [comment]
This really has me stumped.

In my testing, with `foo.10` file (plaintext mimetype) I wasn't able to upload it in anyway inside the media library, despite everything being added and set right inside the FUT settings.

**Comment by sanzeeb3** [comment]
The file is not allowed to upload in anyway, and looks like it shouldn't. I'm only pointing the difference in the uploading mechanism for future reference.

**Comment by sanzeeb3** [comment]
The issue is because `array_merge()` reindexes the numerical keys. `10` is a numerical value. Union `+` can be used because the extensions already allowed by WordPress doesn't need to be overwritten.
