### ISSUE TITLE
Add Custom File Types action icons cleanup

### ISSUE THREAD

**Issue by mattbrett** [awesomemotive/file-upload-types#18]
i'd like to make some minor adjustments to the action icons (plus, trash) in the Add Custom File Types section at the bottom.

- [ ] Add `text-align: right;` to that last column.

- [ ] Add `margin-bottom: -4px;` to the **.file-upload-types-plus, .file-upload-types-minus** selector.

![wpforms-dev test_wp-admin_options-general php_page=file-upload-types (2)](https://user-images.githubusercontent.com/868109/88966526-4cc71e80-d261-11ea-8bcb-ac787cd4ae3c.png)

**Comment by sanzeeb3** [comment]
Closing in favour of #22.
