### ISSUE TITLE
Improve "add your custom file types" link

### ISSUE THREAD

**Issue by jaredatch** [awesomemotive/file-upload-types#19]
When I tested this, I forgot what this link did and thought it was broken. I thought it was going to open the doc. It actually takes the user to the appropriate section on the page, but since I had the settings page open on a big window, it wasn't apparent that anything happened.

Simple and quick fix would be to have the "File Description" field get input focus after click, since we have a nice focus input style.

https://a.cl.ly/rRu76GNW

**Comment by sanzeeb3** [comment]
75722eb Fixes.
