### ISSUE TITLE
Cannot add filetype tar.gz

### ISSUE THREAD

**Issue by francescocmazza** [awesomemotive/file-upload-types#36]
Hello
I'm trying to enable upload of tar.gz files but it won't work.
![SharedScreenshot](https://user-images.githubusercontent.com/30000338/134948058-a9d67165-8221-43cf-a02c-d8a19d10d39f.jpg). 

Don't know if I'm doing something wrong maybe?

Thanks
Francesco

**Comment by sanzeeb3** [comment]
Hey Francesco, the MIME type for the file is incorrect, the standard MIME type is `application/x-gzip`, Other possible MIME types are `application/gzip`, `application/tar`, `application/tar+gzip`. You can add all these mimes separated by a comma. You can also check the correct type of your file by uploading the file [here](https://www.htmlstrip.com/mime-file-type-checker) The extension would be `.gz`.

Please note `.gz` is allowed by default. So, you do not need to use this plugin if the file's MIME type is `application/x-gzip`.

**Comment by francescocmazza** [comment]
Hello Friend. Thank you for your kind feedback.
I tried removing some extra dots in the filename but I still get the same error when uploading this file:
Antminer-L3+-Asicmining-3-8-8.tar.gz
Maybe it's the tar.gz. ? 

also I cannot edit nor delete the custom file extensions I created. Can you please help me get out of this mess? :=)
Thank you very much

**Comment by sanzeeb3** [comment]
@francescocmazza - The extension is usually `.gz` for such file types.  To delete the custom file extensions, you can just uncheck the file types and save the settings. Here's the correct settings: https://a.supportally.com/4ibvdu that might fix the issue. This will override your other setting for this file type so you don't need to edit. If that does not fix it, can you please share your file? You can drag and drop the file right here in the comment to attach.

**Comment by francescocmazza** [comment]
It works!! Thank you so much friend!!

**Comment by sanzeeb3** [comment]
No problem.  :)
