### ISSUE TITLE
\FileUploadTypes\Plugin::real_file_type is not filtering single mime type

### ISSUE THREAD

**Issue by kkarpieszuk** [awesomemotive/file-upload-types#54]
Steps to reproduce:
- register file with extension `.world` and file mime `application/json` (or `text/plain` or `application/octet-stream` see #53 why you need to test different mime types) to be able to upload it
- go to wp-admin > media > add new and try to upload .world file (example here https://drive.google.com/file/d/1Ag6xgybEBvjUxFvo37pOuDTT_sHPTBiw/view )

For now it fails because if there is no multiple mime types registered for extension `\FileUploadTypes\Plugin::real_file_type` is not performing the registration.

**Comment by kennymacharia** [comment]
Adding this here for tracking purposes: https://wordpress.org/support/topic/not-working-with-php-7-4-3-2/

**Comment by cheh** [comment]
The issue with `*. world ` is resolved in #62. I'm closing this GH issue.
