### ISSUE TITLE
.OTF, .TTF and .HEIF files not supported by current version

### ISSUE THREAD

**Issue by kennymacharia** [awesomemotive/file-upload-types#61]
**Helpscout Ticket**: 
https://secure.helpscout.net/conversation/2112530537/2396087?folderId=6939562

## Expected Behavior
The plugin should add support for any listed MIME types after it has been checked in the settings

## Current Behavior
Some file types are not supported and cannot be uploaded to WordPress after their MIME types have been checked in the settings. So far we have confirmed that these types don't work .otf, .ttf, .heic

## Possible Solution
Update the library of supported MIME types

## Steps to Reproduce

1. Go to WordPress > Settings > File Upload Types
2. Check the option to enable OpenType Font Files
3. Head to Media > Add new and try to upload .otf files

## Your Environment
Environment (browser / OS / versions / device / configs etc.): Chrome Browser Version 108.0.5359.125 (Official Build) (64-bit), WordPress 6.1.1
Build version / Addon version / branch: File Upload Types 1.2.2

**Comment by nasanansi** [comment]
.JSON files don't work: https://secure.helpscout.net/conversation/2114005338/2399579/

**Comment by cheh** [comment]
Resolved in #62.
