### ISSUE TITLE
Gulp build task: exclude composer dev-packages

### ISSUE THREAD

**Issue by cheh** [awesomemotive/file-upload-types#65]
The build script for the FUT plugin will need to be updated to exclude the dev-packages in composer.

**Comment by joannafoss** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/WPForms-A-Team-62a0f11261858e0018a7a619/issues/awesomemotive/file-upload-types/65?planning-poker) with Zenhub @kkarpieszuk
