### ISSUE TITLE
Unable to upload .ddd files on PHP 8.3.8

### ISSUE THREAD

**Issue by kennymacharia** [awesomemotive/file-upload-types#78]
A customer reported that they have been using the plugin to upload .DDD files to their site but this suddenly started failing after updating their server's PHP to 8.3. I was able to reproduce the issue using the files that the user shared here: https://we.tl/t-EzcKqWPbQa

Issue report link: https://wordpress.org/support/topic/plugin-not-working-correctly-with-php-8-3/#post-17883640

Screenshots:
PHP 8.2: https://a.supportally.com/i/aJ8jgj
PHP 8.3: https://a.supportally.com/i/ZHRapK

Plugin version: FUT Version 1.3.0

**Comment by kkarpieszuk** [comment]
I see php 8.2 expects this file to have mime type `application/octet-stream` when 8.3 expects `image/x-atari-degas`

I asked customer what type he already defined. If he says the first one, @kennymacharia please answer him to try `image/x-atari-degas`. 

@joannafoss with a new feature we are to be releasing, user will not need such assistance. He will be able to drag and drop file to have the mime type changed (but it will still require manual action to be made, we need to think how to handle such PHP version changes - users can have tens of filetypes defined and we cannot ask them to re-drag each of them).

The best would be if PHP authors inform about such changes...

**Comment by kennymacharia** [comment]
Thank you @kkarpieszuk I have shared this with the user

**Comment by joannafoss** [comment]
@kkarpieszuk @kennymacharia can we close this issue now that v1.4.0 has been released?

**Comment by kennymacharia** [comment]
Hey @joannafoss yep, we can close it! I tested the files and they work well.

**Comment by kkarpieszuk** [comment]
@kennymacharia even though we know customer still has some issues, I am closing this one. I see his current issue is related to this ticket https://github.com/awesomemotive/file-upload-types/issues/77 Please link the forum ticket to 77

I will explain more on the slack
