### ISSUE TITLE
Handling filetypes that PHP's finfo does not know

### ISSUE THREAD

**Issue by matthijskooijman** [awesomemotive/file-upload-types#8]
I've tried this extension (and a couple of others, all fail) to add a custom extension that is not so standard: .scad for application/x-openscad files. These are basically text files with code for the OpenSCAD program.

What seems to happen is that the `upload_mimes` filter adds the type correctly, so the javascript in the editor allows uploading these files. But then, the server-side checks reject the file for security reasons.

What seems to happen on the server side is that Wordpress' `wp_check_filetype_and_ext` function is called to validate the file. This uses PHP's finfo functions to detect the filetype, but they have no idea (so it returns `text/plain`). That does not match the MIME type I have configured in the plugin, so `wp_check_filetype_and_ext` returns failure.

The plugin already has a hook for `wp_check_filetype_and_ext` which allows to return success for all custom filetypes anyway, ignoring the autodetection, based on just the file extension. However, that code only runs when `file_upload_types_strict_check` hook returns false: https://github.com/awesomemotive/file-upload-types/blob/886204d04d2bfa0c40bff61e043da156464ef9fd/includes/class-file-upload-types.php#L175

But I can't find anything about this hook at all in my wordpress installation, nor on Google, how is this supposed to work?

Also, I wonder if it is a good idea to bypass filetype detection entirely for all custom filetypes. Maybe it would be good to instead do this on a per-filetype basis?

One alternative, which seems to work already now, is to put `text/plain` in the mimetype field of the type when adding it in the extension. That might actually be a *good* approach, since it will reject any other non-text files with .scad extension in this example.

Maybe this could be clarified in the plugin admin interface? That the mimetype to be entered is the mimetype that finfo detects such files as? Or, because it's hard for admins to know what finfo will do, you could have an auto-detect feature where you upload a file and then it adds a type with that files extension and detected mimetype automatically?

One further addition could be to configure 2 mimetypes: One that should be detected, and one that should be stored as the mimetype in the medialibrary? This would require returning the detection type from `upload_mimes` and then translating that to the real type in `wp_check_filetype_and_ext`.

Or alternatively, one primary mimetype that is stored in the medialibrary, and 
optional secondary mimetypes that are acceptable as detected filetypes? This has the advantage that it keeps working when finfo learns about the filetype. This would require calling `finfo` again from the plugin's `wp_check_filetype_and_ext` I think.

Note that this seems to be an issue only for text-based formats, since wordpress already allows binary formats unknown to finfo (typically detected as `application/octet-stream`): https://github.com/WordPress/WordPress/blob/248a115c2b994bb0f70accce7a337066cc04f3cc/wp-includes/functions.php#L2870-L2887

**Comment by sanzeeb3** [comment]
Thanks for writing in detail. Yes, the `'wp_check_filetype_and_ext'` check returns the real file type of the file than the autodetection. There's this filter `'file_upload_types_strict_check'` for this specific purpose.

> But I can't find anything about this hook at all in my wordpress installation, nor on Google, how is this supposed to work?

It's the custom filter by this plugin to ignore the real file type check. Returning false will ignore the real file type and the file type configured on the plugin will be allowed for the upload. Example use case:

`add_filter( 'file_upload_types_strict_check', '__return_false' );`

> Maybe it would be good to instead do this on a per-filetype basis?

Yes, thanks for the suggestion. I'll look forward to adding the parameter `$file_data` to this filter to ignore the strict check to the specific file type.

Allowing multiple mime types and a feature to autodetect the file type by uploading the file would be great, I'll make a note to consider it down the road.

**Comment by matthijskooijman** [comment]
> It's the custom filter by this plugin to ignore the real file type check. Returning false will ignore the real file type and the file type configured on the plugin will be allowed for the upload. Example use case:

add_filter( 'file_upload_types_strict_check', '__return_false' );

But how does this work in practice? Does that mean I have to write my own plugin just to add this line? Why is this not just a setting?

**Comment by sanzeeb3** [comment]
Currently, there's no settings for this, unfortunately. In practice, custom codes are added in the theme's functions.php (preferably child theme's). In case it helps, here's a tutorial with ways: https://wpforms.com/developers/how-to-add-custom-php-or-javascript-for-wpforms/

**Comment by sanzeeb3** [comment]
Closing in favour of #21. Multiple mimes can now (since 1.2.0) be added for a single extension.  In this case, both the `application/x-openscad` and `text/plain` for `.scad` extension can be added in the MIME Type section separated by a comma.
