### ISSUE TITLE
Add a message about securing file uploads

### ISSUE THREAD

**Issue by dimitris-am** [awesomemotive/file-upload-types#84]
Hi there,

I think it would be a great addition to include the following message below the file upload types table.  

> While allowing various file uploads can be convenient, it poses security risks.
Enhance your site's security by restricting uploads to specific, safe file types and limiting upload permissions to trusted users only.  
Please refer [here](https://wpforms.com/docs/how-to-allow-additional-file-upload-types/?utm_source=WordPress&utm_medium=fut-help&utm_campaign=file-upload-types&utm_content=view-documentation#secure-upload) for more information.

Probably in a lighter color than the heading!  

Thanks 🍻

**Comment by joannafoss** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/WPForms-A-Team-62a0f11261858e0018a7a619/issues/awesomemotive/file-upload-types/84?planning-poker) with Zenhub @kkarpieszuk
