### ISSUE TITLE
SVG file couldn't be uploaded using Upload Image in Block Editor

### ISSUE THREAD

**Issue by olesia-zhykina** [awesomemotive/file-upload-types#86]
### Current behavior

Customers receive an error when they uploading SVG file using Upload Image in Block Editor. The issue is reproduced when SVG file is allowed to be uploading using FUT Addon.
SVG files could be uploaded using Media Library.

### Expected behavior

SVG files should be allowed to be uploading using Upload Image in Block Editor when it is configured in FUT Addon

### Steps to reproduce

as customer

1. Install, activate UFT Addon
2. Go to WP Settings - UFT Addon, enable SVG file uploading, save changes
3. Go to Pages - Add New Page
4. Click + and choose Image
5. Click Upload button and try to upload file with SVG extension

### Environment where the issue is reproducible

FUT 1.4.0, 1.5.0-RC

### Attachments

https://a.supportally.com/v/m6T2GC

**Comment by kkarpieszuk** [comment]
Olesia could you edit FUT settings and flip (reorder, so it will be `image/svg+xml, application/xml`) the filetypes so to be like this:

![Image](https://github.com/user-attachments/assets/c7f1b1e0-ac72-4a62-9d08-7051d764c064)

and save and tell me if it makes Gutenberg working for you?

**Comment by olesia-zhykina** [comment]
Hello @kkarpieszuk 
Yes, I can confirm that your solution helped me and I can upload SVG file: https://a.supportally.com/v/QPNfU0

@kkarpieszuk, I paid attention that the same issue is reproduced for JSON extension, should I apply the same changes?

**Comment by kkarpieszuk** [comment]
I see you have a really a lot of types defined for json, right? flipping will not work. 

please redefine file type by dropping example file here:

![Image](https://github.com/user-attachments/assets/e93cb511-1071-4b3a-a45f-f6cc80bb0962)

this will give you one file type or two max. 

then check if it works in Gutenberg now. 

if not, and you have two file types, please flip them and see if it helps.

**Comment by olesia-zhykina** [comment]
Thank you @kkarpieszuk for the details, it helped!

I flipped types for the following: https://a.supportally.com/i/lbE2Nb

So do you think we don't need any changes from the code? Or we need to set the right order by default?

**Comment by kkarpieszuk** [comment]
you said you have problems with uploading JSON files but on the last screenshot it is JS file, those are two different kinds of file. Please explain what is the problem (the best would be to provide the test steps or screencast)

**Comment by olesia-zhykina** [comment]
Yes, @kkarpieszuk my bad, everything is good regarding js, json, sorry for confusing. 

The open question is left regarding SVG file, do we need to set the right order of MIME Type by default, or users should update it manually?

**Comment by kkarpieszuk** [comment]
I will check if this is possible to have this set automatically in correct order and if yes, I will prepare the patch.
