### ISSUE TITLE
SVG image is not available on front when it is uploaded using Legacy Widget

### ISSUE THREAD

**Issue by olesia-zhykina** [awesomemotive/file-upload-types#89]
Current behavior
When customers upload SVG image using Legacy Widget, and add it to the page, the image is not available for end users. For issue reproducing SVG file should be allowed.

Expected behavior
SVG image should be displayed properly on the front when they are uploaded using Legacy Widget 

Steps to reproduce
as customer

1. Setup site with WP 5.5 + PHP 7.0
2. Install, activate UFT Addon, 
3. Go to WP Settings - UFT Addon, enable SVG file uploading, save changes
4. Choose theme 2021 in WP Appearance
5. Go to Appearance - Widgets, add Image to e.g. Footer, save changes
6. Check page and image on the front as an end user 

Attachments
https://a.supportally.com/v/GG5m7K

**Comment by olesia-zhykina** [comment]
Please check if this issue is on FUT Addon side, not WP

**Comment by olesia-zhykina** [comment]
Please check if this issue is on FUT Addon side, not WP

**Comment by kkarpieszuk** [comment]
Thank you Olesia. It seems like an issue in wordpress core: image is added but size is set to 1x1px (because SVG files does not have something like size: their size bases on the container size)

https://d.pr/v/oq9gUx
