### ISSUE TITLE
Enhance font color after user enters in new file type

### ISSUE THREAD

**Issue by nmags02** [awesomemotive/file-upload-types#9]
Currently, the font color after a user enters in their custom file type goes to a very, very light grey that can be difficult to see: https://a.supportally.com/s7u61r.

Expected behavior: the color stays black (or some other easily visible color) after file type information has been entered in.

Please let me know if you need any more details (:

**Comment by sanzeeb3** [comment]
yeah, I think black as it is would be better than the very very light grey we have currently. @mattbrett -what do you suggest?

**Comment by mattbrett** [comment]
@sanzeeb3 Agreed, we need to increase the contrast on those fields. How about this...

- [ ] Change the field border color to `#999999` for the default state, and color to `#777777`.
- [ ] Change the focus border color to `#638699`, add `box-shadow: 0 0 0 1px #638699;`, and change text color to `#444444`. This will bring it more inline with the default WP states, but using our own colors.
